/* eslint-disable no-restricted-globals */
import { precacheAndRoute } from "workbox-precaching";

// Precache all the assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

self.addEventListener("install", (event) => {
  console.log("Service worker installing...");
  // Add a call to skipWaiting here if needed
});

self.addEventListener("activate", (event) => {
  console.log("Service worker activating...");
});

self.addEventListener("fetch", (event) => {
  event.respondWith(
    caches.match(event.request).then((response) => {
      return response || fetch(event.request);
    })
  );
});
/* eslint-enable no-restricted-globals */
